### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by alexawesomecode**
#1 What does this Pull Request do?

This Pull request applies all the functionalities of the Smashing magazine

### CODE REVIEW

**Comment by ebukaume** [comment]
Hi @alexawesomecode  and @shemaeric :wave: 

You guys have really done a great job here, but you guys need to make a few required changes.
- [ ] The project has a descriptive README.md (You can refer to [this repo](https://github.com/othneildrew/Best-README-Template) as a guide)

**Footer**
- [ ] It contains centred links (_Your supposed links are centred but they are not actually links yet_).

**Kindly submit another code review request once you have implemented those changes.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by alexawesomecode** [comment]
Hello Ebuka

We solved the changes required. Please take a look. Thanks.

**Comment by ebukaume** [comment]
Hi @alexawesomecode 

Please submit another code review request and an available TSE will attend you ASAP.

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Review by Redvanisation — APPROVED** [review]
### Hello team 🌟 

### _Nice work on this project, it seems that you guys have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
